TOP=../..

include $(TOP)/configure/CONFIG
#----------------------------------------
#  ADD MACRO DEFINITIONS AFTER THIS LINE
#=============================

#==================================================
# build a support library

# install lairdtechPR59Support.dbd into <top>/dbd
DBD += lairdtechPR59Support.dbd

# specify all source files to be compiled and added to the library
#lairdtechPR59_SRCS += xxx
# No sources to compile here..

#===========================

include $(TOP)/configure/RULES
#----------------------------------------
#  ADD RULES AFTER THIS LINE

